### ISSUE TITLE
"Map failed" for any changeset

### ISSUE THREAD

**Issue by literannn** [mapbox/osmcha-frontend#472]
All changesets from yesterday are not displayed - instead of this I see pink screen and "Map failed"

![изображение](https://user-images.githubusercontent.com/46343992/90064366-576ac480-dcf3-11ea-8375-6cff7afb4d88.png)

**Comment by willemarcel** [comment]
@literannn A problem in overpass instance caused a disruption on the changeset map visualization. I believe in some hours we'll have it fixed

**Comment by andrewharvey** [comment]
Looks like this is fixed now

**Comment by literannn** [comment]
Yes, it works

**Comment by thibaultmol** [comment]
Still happens quite often to me (1 hour old changset isn't loading for me)

**Comment by literannn** [comment]
thibaultmol, maybe changeset is not closed?

**Comment by willemarcel** [comment]
@thibaultmol do you have some example of changeset failing to load?
