### ISSUE TITLE
Changeset not visualised at all, no warning of any kind appeared, no progress bar anywhere

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/osmcha-frontend#508]
## *Brief Description*
Visualisation for https://osmcha.org/changesets/96926700/ failed without error.

## What is the motivation / use case for this feature?
I tried to look at https://osmcha.org/changesets/96926700/ to see whatever it looks like upload after long drive across country or baseless random answers.

## What  is the current behaviour, (attach relevant screenshots) ?
No visualization appeared, unlike say https://osmcha.org/changesets/96926600/

![screen05](https://user-images.githubusercontent.com/899988/103624563-fe1d5f00-4f39-11eb-87c6-d299572e5717.jpg)

![screen06](https://user-images.githubusercontent.com/899988/103624629-168d7980-4f3a-11eb-8344-790181280e78.jpg)

(second screen is a victim of another, already reported, bug - but at least something shows up)

## What  is the expected behaviour ?
I see changed elements on a map

## When does this occur ?
Always

## How do we replicate the issue ?

1. Open https://osmcha.org/changesets/96926700/
2. Login with OSM account

## Please tell us about your environment:
Firefox 84.0 on Ubuntu 20.04 flavor Lubuntu

## Other Information / context:
https://overpass-api.de/achavi/?changeset=96926703 also failed, but with a clear error at least

**Comment by willemarcel** [comment]
@matkoniecz we had a problem on the frontend, but it's fixed now and the changeset can be visualized. Thanks for the report.

**Comment by matkoniecz** [comment]
For me it is still failing, in exactly the same way.

I tried to flush browser cache.

**Comment by willemarcel** [comment]
![image](https://user-images.githubusercontent.com/666291/104182976-08cf6c80-53f0-11eb-9c60-4282257cad05.png)

Using the tag changes tab you can zoom to each feature. We'll make some improvements soon to make it easier to visualize changesets with huge bbox.

**Comment by matkoniecz** [comment]
Thanks! I hoped that at least clusters will be shown at zoomed out scale, so I would be able to judge whatever edit was based on blind guessing or is it looking like effect of surveying on a trip.
